---
- name: Import Xen release repo
  yum_repository:
    name: centos-virt-xen-48
    baseurl: http://mirror.centos.org/centos/$releasever/virt/$basearch/xen-48
    gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-Virtualization
    gpgcheck: yes
    enabled: no

- name: Upgrade kernel to latest # noqa 403
  yum:
    name: kernel
    enablerepo: centos-virt-xen-48
    state: latest
  notify: reboot machine
