---
- name: Import Xen release repo
  when: ansible_distribution_major_version == '7'
  yum_repository:
    name: centos-virt-xen-48
    description: CentOS Xen Virtualization SIG 4.8 Repo
    baseurl: http://mirror.centos.org/centos/$releasever/virt/$basearch/xen-48
    gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-Virtualization
    gpgcheck: yes
    enabled: no

- name: Upgrade kernel to latest # noqa 403
  when: ansible_distribution_major_version == '7'
  yum:
    name: kernel
    enablerepo: centos-virt-xen-48
    state: latest
    update_cache: yes
  notify: reboot machine
