---
- name: Install Xen release repo
  when: ansible_distribution_major_version == '7'
  yum:
    name: centos-release-xen-48
    state: present

- name: Set Xen release repo to disable
  yum_repository:
    name: centos-virt-xen-48
    enabled: no

- name: Upgrade kernel to latest # noqa 403
  yum:
    name: kernel
    enablerepo: centos-virt-xen-48
    state: latest

