name: On Push

on:
  push:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install ansible-lint
      run: pip install --upgrade ansible-lint

    - name: Lint source code
      run: ansible-lint tests/test.yml

  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Push code to galaxy
      uses: robertdebock/galaxy-action@1.0.3
      with:
        galaxy_api_key: ${{ secrets.galaxy_api_key }}
